### ISSUE TITLE
Regression with config file in subdirectory (i.e. miniPack)

### ISSUE THREAD

**Issue by vinriviere** [aranym/aranym#24] opened 2019-06-05 19:42 UTC
ARAnyM 1.1.0 has a regression when the config file is located in a subdirectory. ROM files can't be found. This is the case for example with the [miniPack distribution](http://eureka.atari.org/miniPack.zip).

Tested on Windows. It worked fine with ARAnyM 0.9.16. But if you upgrade the ARAnyM binaries with release 1.1.0, it fails like this:

```
run_win.bat
.\bin\aranym-jit.exe -c .\Aranym_files\config
# config file contains: EmuTOS = emutos.img
OS ROM image '.\Aranym_files\.\Aranym_files\emutos.img' not found.
No operating system found. ARAnyM can not boot!
```

Note the double `.\Aranym_files`. That's a nonsense.

**Comment by mikrosk** [comment] 2019-06-06 07:17
Isn't this just another variant of https://github.com/aranym/aranym/issues/21 ? Can you test with latest snapshot?

**Comment by th-otto** [comment] 2019-06-06 10:51
On Mittwoch, 5. Juni 2019 21:42:58 CEST Vincent Rivière wrote:
> ARAnyM 1.1.0 has a regression when the config file is located in a
> subdirectory. 

As Miro already pointed out, this is caused by the same bug that was fixed 
with https://github.com/aranym/aranym/commit/
e85be353c712264a90bc0027d0fc637b37e010af

**Comment by mikrosk** [comment] 2019-06-10 07:05
As seen on aranym mailing list, this has indeed been fixed by using the latest snapshot.

**Closed by mikrosk** 2019-06-10 07:05 UTC

**Comment by vinriviere** [comment] 2019-06-10 07:09
> As seen on aranym mailing list, this has indeed been fixed by using the latest snapshot.

Not really. The miniPack has been updated to workaround this bug.

But I will test a recent ARAnyM snapshot and report the result here.

**Comment by vinriviere** [comment] 2019-06-10 07:26
I confirm this has been fixed in the aranym-1.1.0-cygwin-i386-e85be353-sdl1.zip snapshot. Thanks.

**Comment by th-otto** [comment] 2019-06-10 11:45
>The miniPack has been updated to workaround this bug.

There was no workaround, the executables have been updated with a newer snapshot where the bug was fixed.

**Comment by vinriviere** [comment] 2019-06-10 20:20
File run_win.bat.

Old miniPack:
```
.\bin\aranym-jit.exe -c .\Aranym_files\config
```

New miniPack:
```
cd Aranym_files
..\bin\aranym-jit.exe -c .\config

```
This is a workaround for the bug described here.

**Comment by th-otto** [comment] 2019-06-10 21:11
Oh, ok. Anyway, the bug is already fixed, so it should work with a newer snapshot, or the next release.
