### ISSUE TITLE
Arm snapshots

### ISSUE THREAD

**Issue by sagudev** [aranym/aranym#12] opened 2019-02-26 15:25 UTC
Are there prebuild Arm snapshots? I couldn't find them in [Bintray](https://bintray.com/aranym/aranym-files/snapshots/a9de1ecafae4dec45f0c541981615dfeb3002955?pkgPath=%2Faranym%2Faranym-files%2Fsnapshots#files/snapshots)

**Comment by th-otto** [comment] 2019-02-26 15:45
On Dienstag, 26. Februar 2019 16:25:11 CET sagu wrote:
> Are there prebuild Arm snapshots

No, not yet, as there is no easy way to build them (you can take a look at 
https://github.com/aranym/aranym/blob/master/android/BUILDING to get a start)

**Comment by sagudev** [comment] 2019-02-26 15:47
When I said arm i meant `armhf` like Raspberry PI

**Comment by th-otto** [comment] 2019-02-26 16:17
Essentially, you will need a cross-compiler (Linearo provides them IIRC). Then you configure aranym with

./configure --host=arm-linux-gnueabihf ...

**Comment by sagudev** [comment] 2019-02-27 10:17
https://travis-ci.org/sagudev/aranym/jobs/499172663
checking for XOpenDisplay in -lX11... no
configure: error: Sorry, NatFeat Clipboard not implemented on your platform yet
any idea why this happened?

**Comment by th-otto** [comment] 2019-02-27 11:03
I guess your X11 libraries are missing. You could look at the config.log, if you can grab it somehow from travis

**Comment by sagudev** [comment] 2019-02-27 11:05
I added X11 libs in next commit but still same result. https://travis-ci.org/sagudev/aranym/jobs/499196915

**Comment by th-otto** [comment] 2019-02-27 11:06
Yes, but that are the ones for the host (the ubuntu server travis is running on). You need cross-compiled ones for your target.

**Comment by sagudev** [comment] 2019-03-01 07:22
Where are listed all requirements for building?

**Comment by th-otto** [comment] 2019-03-01 12:59
IIRC, jit for arm FPU does not work currently, or is incomplete at least. You can only enable "normal" jit, without FPU instructions.

**Comment by sagudev** [comment] 2019-03-01 16:26
Tnx. Now the only problem is https://travis-ci.org/sagudev/aranym/jobs/500351454#L9102
make: *** No rule to make target 'install-strip'.  Stop.

**Comment by th-otto** [comment] 2019-03-01 18:43
Hm, no idea currently, maybe some older automake version that does not create that target? You could change that to just "make install", at least for testing.

BTW interesting attempt you take there (using a raspian image, chroot & qemu to build the package natively rather than using cross compiler). Let me know if this works. Might be a matter of build time also, since travis jobs are limited (i think 40min or so).

Also you should maybe silence your wget somehow. It spits out ~7000 log lines, and travis jobs are limited to 10000 lines, after that the jobs gets aborted.

Since your are using qemu anyway, you might also consider testing your script locally first, that should give you the option to look at any log files that are left behind.

**Comment by sagudev** [comment] 2019-03-01 19:59
I will check automake version.

> 

> BTW interesting attempt you take there (using a raspian image, chroot & qemu to build the package natively rather than using cross compiler). Let me know if this works. Might be a matter of build time also, since Travis jobs are limited (i think 40min or so).

I split building of mmu, jit, and normal aranym build in separate jobs. Travis job limit is 50min

> Also you should maybe silence your wget somehow. It spits out ~7000 log lines, and Travis jobs are limited to 10000 lines, after that the jobs gets aborted.

I'm aware of that but I always forget to add -q switch to wget.

> Since your are using qemu anyway, you might also consider testing your script locally first, that should give you the option to look at any log files that are left behind.

I want to check if it work in Travis and that's why I am using dev branch with a lot of small commits. When I will merge to my master I will do rebase.

**Comment by sagudev** [comment] 2019-03-02 06:56
When I put normal + mmu build together I do not get this error. But in normal + jit build time exceeded the maximum time. https://travis-ci.org/sagudev/aranym/builds/500689183

**Comment by th-otto** [comment] 2019-03-02 08:06
Yes, that could be expected. JIT involves building the compiler sources first, and then compiiing them. It is  rather large, that's why it is already compiled compiled in 8 steps. But since you have to split the jobs anyway, you don't have to compile two of them in a single job. Just find a way to put the pieces together once they are built, since there should be a single archive at the end.

And another idea: once you have a working version, you could use that to compile the next one, instead of using qemu ;)

**Comment by sagudev** [comment] 2019-03-02 09:49
Is there any way to build just jit and just mmu without normal build?

**Comment by sagudev** [comment] 2019-03-02 10:13
> Just find a way to put the pieces together once they are built, since there should be a single archive at the end.

Maybe https://docs.travis-ci.com/user/build-stages/#how-do-build-stages-work

**Comment by th-otto** [comment] 2019-03-02 11:00
Which configuration is build, just depends on the configure flags. Default is to build a normal version. mmu version is build by specifying --full-mmu (and usually also --enable-lilo). jit is build by specying --enable-jit-compiler (and maybe --enable-jit-fpu). Each version must be configured separately, and with a clean directory.
The rpm spec file handles this for example by doing a sequence of
- configure for jit
- make
- mv aranym aranym-jit
- make clean
- configure for mmu
- make
- mv aranym aranym-mmu
- make clean
- configure normal

After that, there are 3 executables. Since you are building the separate versions in different jobs, you have to find a way to save the resulting executable after each job, since they run in parallel, in different VMs.

**Comment by sagudev** [comment] 2019-03-02 11:02
I will save them to Bintray and then remove them on successful deploy.

**Comment by sagudev** [comment] 2019-03-02 15:14
Not the last [build](https://travis-ci.org/sagudev/aranym/builds/500816393) but it is 80% finished (if something doesn't go wrong).

**Comment by sagudev** [comment] 2019-03-03 15:32
Now i have this error at https://travis-ci.org/sagudev/aranym/jobs/501065469#L504 on [commit 77ec7e5](https://github.com/sagudev/aranym/tree/77ec7e560b9ac65bfadc61b313379ee93a639bfa)

appimagetool, continuous build (commit 7d45aa3), build 2046 built on 2019-02-11 22:41:20 UTC
/home/travis/build/sagudev/aranym/appimage/ARAnyM.AppDir/aranym.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated

Name: ARAnyM

Icon: aranym

Exec: aranym.wrapper

Comment: Virtual Machine for Atari 32-bit applications

Type: Application

Categories: System;Emulator;

/home/travis/build/sagudev/aranym/appimage/ARAnyM.AppDir/usr/bin/aranym used for determining architecture armhf

/home/travis/build/sagudev/aranym/appimage/ARAnyM.AppDir/usr/bin/aratapif used for determining architecture armhf

/home/travis/build/sagudev/aranym/appimage/ARAnyM.AppDir/AppRun used for determining architecture x86_64

More than one architectures were found of the AppDir source directory "./ARAnyM.AppDir/"

A valid architecture with the ARCH environmental variable should be provided

e.g. ARCH=x86_64 appimagetool ...

Desktop file: /home/travis/build/sagudev/aranym/appimage/ARAnyM.AppDir/aranym.desktop

**Comment by th-otto** [comment] 2019-03-03 15:50
That's because of a wrong version of the "AppRun" executable, which is responsible for launching the application. I'm not sure whether you need AppImages at all on raspbian, but if you wont to support them, you will need a version of that tool for arm. Maybe you just have to set ARCH  to armhf beore running the script to build the AppImage, like mentioned in the log file.

**Comment by joysfera** [comment] 2019-03-03 16:16
Thorsten Otto píše v Ne 03. 03. 2019 v 07:50 -0800:
> you need AppImages at all on raspbian

I'd skip AppImage building for ARM devices, they all run on Debian,
luckily.

**Comment by sagudev** [comment] 2019-03-03 16:49
Here new build: https://travis-ci.org/sagudev/aranym/builds/501135955 but still same error.

**Comment by th-otto** [comment] 2019-03-03 16:59
I think the problem is that the appimage/build.sh script runs on the ubuntu (x86) machine. You have to run it inside your arm debian image, since it also copies some shared libraries of the target system to the appimage folder.

**Comment by sagudev** [comment] 2019-03-05 10:01
This is new problem: https://travis-ci.org/sagudev/aranym/jobs/501635204#L1946
/home/travis/build/sagudev/aranym/appimage/functions.sh: line 238: ./appimagetool: cannot execute binary file: Exec format error

**Comment by sagudev** [comment] 2019-03-05 15:44
https://github.com/AppImage/AppImageKit/issues/828 has same problem so and he provided temporary fix. I hope it will work.

**Comment by sagudev** [comment] 2019-03-06 15:59
I checked and binary's are working but appimage building don't. So I will try to create armhf and amd64 snap.

**Comment by sagudev** [comment] 2019-03-16 16:12
On snap store says 

> The snap name "aranym" is reserved.

but there is no aranym snap in store. Did you reserve it?

**Comment by th-otto** [comment] 2019-03-16 16:54
No, but maybe Petr?

**Comment by joysfera** [comment] 2019-03-16 16:55
I can't remember doing that.

**Comment by joysfera** [comment] 2019-03-16 17:01
FYI, known applications got their names reserved. Now "a snap name dispute must be filed to get access to the name."

**Comment by th-otto** [comment] 2019-03-16 17:05
Yes, i think so. You can't use a name that is already used as a package name in common distros.

**Comment by joysfera** [comment] 2019-03-16 17:08
I asked them for giving me the name.

**Comment by sagudev** [comment] 2019-03-16 18:23
Ok, for now I am using sagudev-aranym for testing.

**Comment by sagudev** [comment] 2019-03-17 12:18
Armhf snap is working. Amd64 snap still has some problems:

found errors in file output: unusual mode 'rwsr-xr-x' for entry './usr/bin/aratapif' security-snap-v2_squashfs_files
checksums do not match. Please ensure the snap is created with either 'snapcraft pack <DIR>' (using snapcraft >= 2.38) or 'mksquashfs <dir> <snap> -noappend -comp xz -all-root -no-xattrs -no-fragments'. If using electron-builder, please upgrade to latest stable (>= 20.14.7). See https://forum.snapcraft.io/t/automated-reviews-and-snapcraft-2-38/4982/17 for details. security-snap-v2_squashfs_repack_checksum

You can see snap on https://snapcraft.io/sagudev-aranym

**Comment by th-otto** [comment] 2019-03-17 12:39
Thats because aratapif has to be setuid root to be usable. Normally that is tken care of by the the Package installer, after archive has been extracted. There is also a self-check in aratapif. That program is oly used if you configure the net interface to use a tap device.

**Comment by sagudev** [comment] 2019-03-17 13:22
Oh, I see. And in deploy stage at arm those file permissions probably go away because of extracting and another taring.

**Comment by sagudev** [comment] 2019-03-17 14:26
I untar with `tar xf *.tar.xz` and tar back with `tar cvfJ hi.tar.xz .` and now everything works. Now I will implement this in Travis and check if snaps working.

EDIT: I do not have any armhf device, could someone test armhf snap for me.

**Comment by sagudev** [comment] 2019-03-17 16:30
I have created snaps and automated builds are working. Is really needed for Aranym to be built in trusty?

**Comment by th-otto** [comment] 2019-03-17 16:36
I haven't tried others yet. Maybe packages are changed. Also, when compiling on newer versions you risk that the executable does not run on older version anymore. But you can try.

**Comment by joysfera** [comment] 2019-03-17 16:38
@sagudev , Trusty is no longer supported by us as it will end in about month. Only Xenial and Bionic.
I could test the armhf, I've got both Orange Pi and Raspberry Pi.

**Comment by sagudev** [comment] 2019-03-17 16:40
I'm asking because I already create it.
See for yourself: https://travis-ci.org/sagudev/aranym/jobs/507500818
I moved to Xenial because snaps are for supported on Xenial but not on trusty.

**Comment by joysfera** [comment] 2019-04-15 17:27
@sagudev FYI, I have just asked for the 'aranym' name on the snap store again. Hopefully it'll go through this time.

**Comment by sagudev** [comment] 2019-04-15 17:44
Didi they reject first time? Why?

**Comment by joysfera** [comment] 2019-04-15 17:46
I have been trying to prove that I am me. I use three different emails so maybe that's why they didn't believe me originally. I hope it'll work better this time.

**Comment by sagudev** [comment] 2019-04-15 17:49
Good luck.

**Comment by joysfera** [comment] 2019-04-15 22:35
@sagudev , I have just got the following reply:

> Your "aranym" registration has been approved.
> Thanks for your patience and providing the requested info. This is approved now, happy snapping!
> You can now upload your snap at https://dashboard.snapcraft.io/upload/

How are we going to proceed? Can I delegate the upload rights to you? Or should I re-upload the snap you created? Or is there something more automated perhaps?

**Comment by sagudev** [comment] 2019-04-16 04:28
Create snap on https://snapcraft.io/ called aranym (you need to create ubuntu one account I think)
You will need Linux machine with https://snapcraft.io/snapcraft (can be vm)
Create Snapcraft token with `snapcraft export-login --snaps aranym -`
Add `SNAP_TOKEN=<your_snapcraft_token_here>` to Travis just like you added Bintray api key.
And then merge PR.

**Comment by sagudev** [comment] 2019-05-17 16:23
Any progress yet?

**Comment by joysfera** [comment] 2019-05-26 20:02
This is what I got - please note the last line, that stops me from commiting it to Travis.

```
snaps:       ['aranym']
channels:    No restriction
permissions: ['package_access', 'package_manage', 'package_push', 'package_register', 'package_release', 'package_update']
expires:     2020-05-25T20:00:23.891416
```
**This exported login is not encrypted. Do not commit it to version control!**

**Comment by sagudev** [comment] 2019-05-27 13:20
This just says that you shouldn't print it or show it to anybody. Its like API key of Bintray. So save it like Bintray API key using secret.

**Comment by joysfera** [comment] 2019-06-10 21:14
@sagudev it's finally there. Sorry it took me ages.

**Comment by sagudev** [comment] 2019-06-11 04:11
@joysfera It looks like something is still wrong:
Invalid login config: File contains no section headers.
file: '<string>', line: 1
'[secure]\n'
https://travis-ci.org/aranym/aranym/jobs/543945761#L627

**Comment by sagudev** [comment] 2019-06-11 05:49
Potential fix is in #28

**Comment by joysfera** [comment] 2019-06-11 06:27
I have just committed a different potential fix that adds double quotes around the token at a different place. Let's see if it helps.

Your #28, after it is corrected, could be committed as well, if my double quotes fix didn't help.

BTW, I have tested the echo "<token>" | snapcraft login on my bash prompt in Ubuntu and it worked OK, but I don't know if dash or what is running on the travis can handle 3265 chars long env. variables.

**Comment by sagudev** [comment] 2019-06-11 12:15
Your fix is working. But I saw another problem armhf snap is not built but amd64 is built twice.

**Comment by joysfera** [comment] 2019-06-11 12:32
Sounds like we're getting there. Can't wait to fix this last thing and then announce the snaps :-)

**Comment by sagudev** [comment] 2019-06-11 12:35
I'm testing fix already.
https://travis-ci.org/sagudev/aranym/builds/544199797

BTW: We only have snaps for armhf and amd64 because of automated builds. What about other architectures?

**Comment by paulwratt** [comment] 2019-06-11 12:50
so I can try the armhf builds?

**Comment by sagudev** [comment] 2019-06-11 12:51
Soon

**Comment by joysfera** [comment] 2019-06-11 12:56
@sagudev you mean i386 and arm64? Yes, why not?

**Comment by sagudev** [comment] 2019-06-11 12:59
Yes. Wait does aranym supports arm64?

**Comment by sagudev** [comment] 2019-06-11 13:54
Fix is ready in #29

**Comment by th-otto** [comment] 2019-06-11 15:40
>Yes. Wait does aranym supports arm64?

The JIT compiler does not yet support aarch64. The normal+mmu versions should work, though.

**Comment by sagudev** [comment] 2019-06-12 04:03
Could someone try armhf snap on Raspbery pi?
I will try to add support for aarch64 and i386 in next week. I will probably crosscompile for i386 and use emulator for aarch64.

**Comment by th-otto** [comment] 2019-06-12 04:12
>use emulator for aarch64.

If you get this working, please let me know. Last time i tried (using qemu) it basically worked, but only by redirecting output to the host console. I could not get keyboard and mouse working for PI3, looks like it is not supported yet in their board configurations.

**Comment by sagudev** [comment] 2019-06-12 04:19
This is because Raspbian is only for armhf architecture. In armhf build we already use Qemu-arm with raspbian, so now I will use qemu-aarch64 with xenial-server-cloudimg-arm64 for aarch64.
https://wiki.ubuntu.com/ARM64/QEMU

**Comment by th-otto** [comment] 2019-06-12 04:27
Yes, that will work for building and/or cross-compiling aranym, but not to run it there. You could maybe run it headless, but that is rather pointless for testing.

**Comment by sagudev** [comment] 2019-06-12 04:37
I tested tared armhf build on qemu-armhf with raspbian and it worked, but it was really slow. So I will let testing Snaps to armhf/aarch64 device owners.

**Comment by sagudev** [comment] 2019-06-13 04:41
Which host flag I need to use to cross-compile to i386 in configure.

./configure --host=???

**Comment by th-otto** [comment] 2019-06-13 06:24
Usually, --host=i686-pc-linux. Just look at the name the cross-compiler was installed. I'm not sure however whether cross-compiling actually works for aranym, since some of the tools need to be compiled by the native compiler, (gencpu etc, those are run afterwards to generate some sources).

**Comment by sagudev** [comment] 2019-06-13 15:26
What about aliasing native compiler to cross-compile?

**Comment by sagudev** [comment] 2019-06-14 16:56
I am finalizing i386 building. Firstly I reordered build system and then I use chroot in mix of mk-sbuild to start building. Because in this chroot QEMU is not needed build is finished and deployed in one job.

**Comment by sagudev** [comment] 2019-06-15 09:04
Could someone test i386 snap from here: https://snapcraft.io/sagudev-aranym

**Comment by th-otto** [comment] 2019-06-24 10:27
One of the last builds failed for armhf. Also, one of the other was build successfully in ~5min,  while it usually takes ~28min. Something strange is going on there. Could you have a look?

**Comment by sagudev** [comment] 2019-06-24 13:07
On #33 everything worked. Maybe travis update xenial vm? I will take a look.

`qemu: Unsupported syscall: 384` was printed whenever you looked at armhf build. You can skip it.

**Comment by sagudev** [comment] 2019-06-24 13:15
Could you rerun the build.

**Comment by th-otto** [comment] 2019-06-24 17:11
Just did, same result. Strangely, the first job is reported as successfull, but has the same errors.

The build from the commit before that (https://travis-ci.org/aranym/aranym/jobs/549483734, only a few hours ago) did not have that problem.

**Comment by sagudev** [comment] 2019-06-24 18:22
Could you rerun last successful build.

**Comment by th-otto** [comment] 2019-06-24 22:12
That fails now too. Looks like they have messed up the image somehow, or something bogus gets installed by apt-get update. Lets wait a few days and try again.

**Comment by th-otto** [comment] 2019-06-29 03:58
What a crap, still failing. Do you have a ubuntu xenial installation, and does it work there?

**Comment by sagudev** [comment] 2019-06-29 12:42
When I was testing I was using lxc with ubuntu container. The most weird thing is that first few days all was working.

**Comment by sagudev** [comment] 2019-06-29 16:20
![slika](https://user-images.githubusercontent.com/16504129/60386809-6617fd00-9a9a-11e9-9c6f-3dd196c8bd73.png)
Maybe we should ask Travis-Ci, because it looks like their fault.

**Comment by sagudev** [comment] 2019-06-29 16:29
At https://docs.travis-ci.com/user/build-environment-updates/ it looks like they do not updated vm image for a few months, so I will check if any dependencies apt package updated.

**Comment by th-otto** [comment] 2019-06-30 01:50
Ah, that's the image you use for qemu, not the one travis is running on. That might explain something. You are referencing "raspbian_lite_latest", any way to get at the previous, working version?

**Comment by th-otto** [comment] 2019-06-30 03:10
Edit: saw that you opened already a PR, and merged it. That finally solved it, thanks for all your efforts. A bit strange that their "latest" release is buster, which is not even yet released.

**Closed by th-otto** 2019-06-30 03:10 UTC

**Comment by joysfera** [comment] 2019-06-30 06:24
@th-otto , FYI, they needed a new stable OS for the new Raspberry Pi 4 and the Stretch was too old for keeping it up to date for next several years so they jumped straight to freezed Buster that will be released in two weeks already.

**Comment by sagudev** [comment] 2019-06-30 06:28
But we should continue build armhf builds on Stretch for backwards-compatibility for at least a year or till Stretch support end.

**Comment by joysfera** [comment] 2019-06-30 06:30
Right, they keep backwards compatibility for existing binaries even on RPi4, so building Stretch based binaries is perfectly OK.

**Comment by sagudev** [comment] 2019-06-30 14:18
I am currently finalizing aarch64 builds, so I was thinking if we could make new release, after I finished, to test if automated releasing now works.

**Comment by th-otto** [comment] 2019-06-30 14:36
Are they usable anywhere? From what i read, even on RPi4 the 64bit version of debian will not be ready for quite some time.

**Comment by joysfera** [comment] 2019-06-30 15:01
@sagudev I'd love to make a new release but regressions are still popping up (#36) so ARAnyM is not ready for releasing yet. Once it settles a bit I'll make a new release, don't worry.

**Comment by sagudev** [comment] 2019-06-30 15:07
@th-otto But ubuntu for RPi is aarch64: https://ubuntu-mate.org/raspberry-pi/ https://wiki.ubuntu.com/ARM/RaspberryPi
